default_platform(:android)

platform :android do
  desc "Lane For Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons -v"
    firebase_app_distribution(
    app: "1:416681203570:android:b21dfa02d93d02a60cafeb",
    firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
    android_artifact_type: "APK",
    android_artifact_path: "../build/app/outputs/apk/production/release/app-production-release.apk",
    testers: "2004ahmadhomsy@gmail.com,abdullrazak.moj@gmail.com",
    release_notes: "First Fastlane Firebase Distribution",
    upload_timeout: 1800
  )  end
end
